name: Build Cross-Platform Executables

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:  # Allow manual triggering

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        if (Test-Path requirements.txt) { pip install -r requirements.txt }

    - name: Validate build requirements
      run: |
        python validate_build.py

    - name: Build Windows executable
      run: |
        .\build_windows.bat
      shell: cmd

    - name: Verify Windows build
      run: |
        if (Test-Path "dist/PDF_Processor.exe") {
          Write-Host "✅ Windows build successful!"
          Get-Item dist/PDF_Processor.exe | Select-Object Name, Length, LastWriteTime
        } else {
          Write-Host "❌ Windows build failed"
          exit 1
        }

    - name: Test Windows executable
      run: |
        Write-Host "🧪 Testing Windows executable..."
        $exePath = "dist/PDF_Processor.exe"
        if (!(Test-Path $exePath)) {
          Write-Host "❌ Executable not found: $exePath"
          exit 1
        }
        Write-Host "✅ Executable exists and is ready for testing"

    - name: Upload Windows artifact
      uses: actions/upload-artifact@v4
      with:
        name: PDF-Processor-Windows
        path: dist/PDF_Processor.exe
        retention-days: 30

  build-macos:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install system dependencies
      run: |
        brew update
        brew install python-tk

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Validate build requirements
      run: |
        python validate_build.py

    - name: Make build script executable
      run: |
        chmod +x build_macos.sh

    - name: Build macOS app
      run: |
        ./build_macos.sh

    - name: Verify macOS build
      run: |
        if [ -d "dist/PDF Processor.app" ]; then
          echo "✅ macOS build successful!"
          du -sh "dist/PDF Processor.app"
          echo "Contents:"
          ls -la "dist/PDF Processor.app/Contents/MacOS/"
        else
          echo "❌ macOS build failed"
          exit 1
        fi

    - name: Test macOS app startup
      run: |
        echo "🧪 Testing macOS app startup..."
        EXECUTABLE="dist/PDF Processor.app/Contents/MacOS/PDF Processor"
        if [ ! -f "$EXECUTABLE" ]; then
          echo "❌ Executable not found: $EXECUTABLE"
          exit 1
        fi
        
        # Check executable permissions
        if [ ! -x "$EXECUTABLE" ]; then
          echo "🔧 Making executable..."
          chmod +x "$EXECUTABLE"
        fi
        
        echo "📋 Executable information:"
        ls -la "$EXECUTABLE"
        file "$EXECUTABLE"
        
        # Test 1: Basic file validation
        echo "Test 1: Basic file validation..."
        if [ -x "$EXECUTABLE" ]; then
          echo "✅ Executable has execute permissions"
        else
          echo "❌ Executable missing execute permissions"
          exit 1
        fi
        
        # Test 2: Quick startup test (shorter timeout)
        echo "Test 2: Quick startup test..."
        START_TIME=$(date +%s)
        
        # Try to start the app in background with shorter timeout
        "$EXECUTABLE" > /tmp/app_startup.log 2>&1 &
        APP_PID=$!
        
        # Wait up to 5 seconds (shorter than before)
        SECONDS_WAITED=0
        while kill -0 $APP_PID 2>/dev/null && [ $SECONDS_WAITED -lt 5 ]; do
          sleep 1
          SECONDS_WAITED=$((SECONDS_WAITED + 1))
          echo "⏳ Waiting... $SECONDS_WAITED seconds"
        done
        
        END_TIME=$(date +%s)
        DURATION=$((END_TIME - START_TIME))
        
        # Check result
        if kill -0 $APP_PID 2>/dev/null; then
          echo "✅ App started successfully (still running after $SECONDS_WAITED seconds)"
          echo "🛑 Killing test process..."
          kill $APP_PID 2>/dev/null || true
          sleep 1
          if kill -0 $APP_PID 2>/dev/null; then
            kill -9 $APP_PID 2>/dev/null || true
          fi
        else
          wait $APP_PID 2>/dev/null
          EXIT_CODE=$?
          echo "📊 App exited with code: $EXIT_CODE (duration: ${DURATION}s)"
          
          if [ $EXIT_CODE -eq 0 ]; then
            echo "✅ App started and exited cleanly"
          elif [ $EXIT_CODE -eq 137 ]; then
            echo "⚠️  App was killed (SIGKILL) - this may be normal for GUI apps"
            echo "   GUI applications often get killed in CI environments"
            echo "   This doesn't necessarily indicate a problem with the app"
          else
            echo "⚠️  App exited with code: $EXIT_CODE"
            echo "Output from app:"
            cat /tmp/app_startup.log 2>/dev/null || echo "No output captured"
          fi
        fi
        
        # Test 3: Check app bundle structure
        echo "Test 3: App bundle structure check..."
        if [ -d "dist/PDF Processor.app" ]; then
          echo "✅ App bundle directory exists"
          
          if [ -f "dist/PDF Processor.app/Contents/Info.plist" ]; then
            echo "✅ Info.plist exists"
          else
            echo "⚠️  Info.plist not found"
          fi
          
          if [ -d "dist/PDF Processor.app/Contents/MacOS" ]; then
            echo "✅ MacOS directory exists"
            echo "Contents: $(ls -la 'dist/PDF Processor.app/Contents/MacOS/')"
          else
            echo "⚠️  MacOS directory not found"
          fi
          
          if [ -d "dist/PDF Processor.app/Contents/Resources" ]; then
            echo "✅ Resources directory exists"
          else
            echo "ℹ️  Resources directory not found (may be normal)"
          fi
        else
          echo "❌ App bundle directory not found"
          exit 1
        fi
        
        # Clean up
        rm -f /tmp/app_startup.log
        echo "✅ macOS app is ready for testing"

    - name: Set macOS executable permissions
      run: |
        echo "🔧 Setting executable permissions..."
        chmod 755 "dist/PDF Processor.app/Contents/MacOS/PDF Processor"
        ls -la "dist/PDF Processor.app/Contents/MacOS/PDF Processor"

    - name: Create macOS distribution archive
      run: |
        echo "📦 Creating macOS distribution archive with ditto..."
        ditto -c -k --sequesterRsrc --keepParent "dist/PDF Processor.app" "PDF-Processor-macOS-App.zip"
        ls -la PDF-Processor-macOS-App.zip

    - name: Upload macOS artifact
      uses: actions/upload-artifact@v4
      with:
        name: PDF-Processor-macOS
        path: |
          dist/PDF Processor.app/
          PDF-Processor-macOS-App.zip
        retention-days: 30

  create-release:
    needs: [build-windows, build-macos]
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download Windows artifact
      uses: actions/download-artifact@v4
      with:
        name: PDF-Processor-Windows
        path: artifacts/windows/

    - name: Download macOS artifact
      uses: actions/download-artifact@v4
      with:
        name: PDF-Processor-macOS
        path: artifacts/macos/

    - name: Create release archives
      run: |
        cd artifacts
        # Create Windows archive
        zip -r PDF_Processor_Windows.zip windows/
        # Create macOS archive with ditto to preserve permissions
        cd macos
        ditto -c -k --sequesterRsrc --keepParent "PDF Processor.app" "../PDF_Processor_macOS.zip"
        cd ..
        # Create combined archive
        zip -r PDF_Processor_All_Platforms.zip windows/ macos/

    - name: Create GitHub Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ github.run_number }}
        release_name: PDF Processor v${{ github.run_number }}
        body: |
          ## 🚀 Automated Release

          This release contains the latest PDF Processor executables for Windows and macOS.

          ### 📦 Downloads:
          - **Windows**: `PDF_Processor_Windows.zip` - Standalone .exe file
          - **macOS**: `PDF_Processor_macOS.tar.gz` - Native macOS .app bundle
          - **All Platforms**: `PDF_Processor_All_Platforms.zip` - Combined archive

          ### ✨ Features:
          - Batch PDF processing with modern GUI
          - Automatic text replacement with formatting preservation
          - JSON-based dynamic PDF generation
          - Cross-platform compatibility

          ### 🛠️ Installation:
          - **Windows**: Extract and run `PDF_Processor.exe`
          - **macOS**: Extract and double-click `PDF Processor.app`

          No Python installation required!
        draft: false
        prerelease: false

    - name: Upload release assets
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: artifacts/PDF_Processor_Windows.zip
        asset_name: PDF_Processor_Windows.zip
        asset_content_type: application/zip

    - name: Upload macOS release asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: artifacts/PDF_Processor_macOS.tar.gz
        asset_name: PDF_Processor_macOS.tar.gz
        asset_content_type: application/gzip

    - name: Upload combined release asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: artifacts/PDF_Processor_All_Platforms.zip
        asset_name: PDF_Processor_All_Platforms.zip
        asset_content_type: application/zip
